# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-std:
    docker:
      - image: ajjjjjjjj/opentx-docker-i6x:1.4.0
    steps:
      - checkout
      - run: |
          python3 ./tools/build-flysky.py -bI6X -tDE $PWD/
      - store_artifacts:
          path: output

  

workflows:
  openi6x-release-workflow:
    jobs:
      
      - build-std:
          filters:
            branches:
              only:
                - pulseref
            
      
      
      
